language: java
dist: xenial
sudo: true

jdk:
  - oraclejdk8

script: 
  # - jdk_switcher use oraclejdk8
  - ./download_processing.sh
  - ./build.sh

after_failure:
  - find . | egrep "processing-java"

after_success:
  - find . | egrep "processing-java"
